rvm: '2.5.1'

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database chitter_test;'
  - psql -c "CREATE TABLE users (id SERIAL PRIMARY KEY, password VARCHAR(140), name VARCHAR(60), username VARCHAR(60) UNIQUE, email VARCHAR(60) UNIQUE);"
  - psql -c "CREATE TABLE peeps (id SERIAL PRIMARY KEY, text VARCHAR(144), time VARCHAR(32), hidden_timestamp TIMESTAMPTZ, user_id INTEGER REFERENCES users (id), user_username VARCHAR(60) REFERENCES users (username));"
